package ru.mirea.uibo02.trukhachev;

import java.util.Arrays;
import java.util.Random;
import java.util.Scanner;



public class main {
    public static void main(String[] args)
    {
        tsk3();
        tsk4(args);
        tsk5();
        tsk6();
        tsk7();
    }

    public static void tsk3()
    {
        int[] data = {0, 1, 2, 3, 4, 5};
        int sum = 0;
        for(int i = 0; i < data.length; i++)
        {
            sum += data[i];
        }
        System.out.println("summa for = " + sum);

        int[] data1 = {0, 1, 2, 3, 4, 5};
        int sum1 = 0;
        int a = 0;
        while(a < data1.length)
        {
            sum1 += data1[a];
            a++;
        }
        System.out.println("summa while = " + sum1);

        int[] data2 = {0, 1, 2, 3, 4, 5};
        int sum2 = 0;
        int b = 0;
        do
        {
            sum2 += data2[b];
            b++;
        }
        while
        (
                b < data2.length
        );
        System.out.println("summa do while = " + sum2);
    }

    public static void tsk4(String[] args)
    {
        for (int i = 0; i < args.length; i++)
        {
            System.out.println(args[i]);
        }
    }

    public static void tsk5()
    {
        int n = 10;
        double sum = 0.0;

        for (int i = 1; i <= n; i++)
        {
            sum += 1.0 / i;
            System.out.printf("%.2f ", sum);
        }
        System.out.println();
    }

    public static void tsk6() {
        int[] arraym = new int[10];
        for (int i = 0; i < arraym.length; i++)
        {
            arraym[i] = (int) (Math.random() * 100);
        }
        System.out.println("Generated by math array: ");
        System.out.println(Arrays.toString(arraym));
        Arrays.sort(arraym);
        System.out.println("Sorted array: ");
        System.out.println(Arrays.toString(arraym));

        Random random = new Random();
        int[] arrayr = new int[10];
        for(int i = 0; i < arrayr.length; i++)
        {
            arrayr[i] = random.nextInt(100);
        }
        System.out.println("Generated by random array: ");
        System.out.println(Arrays.toString(arrayr));
        Arrays.sort(arrayr);
        System.out.println("Sorted array: ");
        System.out.println(Arrays.toString(arrayr));
    }

    public static void tsk7()
    {
        Scanner scanner = new Scanner(System.in);
        System.out.print("Enter: ");
        int number = scanner.nextInt();
        scanner.close();
        int factor = 1;
        for(int i = 1; i <= number; i++)
        {
            factor *= i;
        }
        System.out.println("Factorial " + number + "is: " + factor);
    }
}
